#!/usr/bin/env python3
from pathlib import Path
import re,sys,html
ROOT=Path(sys.argv[1] if len(sys.argv)>1 else '_site')

def p(route): return ROOT/route.strip('/')/'index.html'
def replace(route, main):
 f=p(route); src=f.read_text(encoding='utf-8'); src,n=re.subn(r'<main\b[^>]*id="main-content"[^>]*>.*?</main>',main,src,count=1,flags=re.S|re.I)
 if n!=1: raise SystemExit(f'stage130: main replace failed {route}')
 f.write_text(src,encoding='utf-8')

def hero(kicker,title,lead,side_title,side):
 return f'''<section class="p130-hero"><div class="p130-shell p130-hero-grid"><div><p class="p130-kicker"><i></i>{kicker}</p><h1>{title}</h1><p class="p130-lead">{lead}</p></div><aside class="p130-hero-side"><strong>{side_title}</strong>{side}</aside></div></section>'''

def rows(items):
 return ''.join(f'<a class="p130-row" href="{u}"><span>{i:02d}</span><strong>{html.escape(t)}</strong><em>{html.escape(d)}</em><b>↗</b></a>' for i,(u,t,d) in enumerate(items,1))

services=[
('/web-development/','Сайты и веб-сервисы','Лендинги, каталоги, кабинеты, SaaS и внутренние продукты.'),('/telegram-bots/','Telegram-продукты','Боты и пользовательские сценарии внутри Telegram.'),('/app-development/','Мобильные приложения','Пользовательский путь от первого экрана до рабочего результата.'),('/n8n-automation/','Автоматизация','Убрать повторяющиеся действия и связать используемые сервисы.'),('/api-integrations/','Интеграции','Передавать данные между сайтом, CRM, Telegram, платежами и другими системами.'),('/crm-development/','CRM и внутренние системы','Рабочий контур для заявок, статусов, клиентов и сотрудников.'),('/project-repair/','Доработка проекта','Продолжить чужой код, исправить ошибку или довести незавершённый релиз.'),('/mvp-development/','MVP','Проверить идею первой законченной версией продукта.'),('/python-development/','Python','Серверная логика, боты, данные и прикладные инструменты.'),('/ios-development/','iOS / Swift','Нативные сценарии для iPhone и iPad.')]
services_main=f'''<main id="main-content" class="p130-hub" data-stage130-hub="services">{hero('SERVICES','Не выбирайте технологию. <span>Выберите результат.</span>','Если уже знаете стек — отлично. Если нет, достаточно описать, что пользователь или сотрудник должен суметь сделать после запуска.','Прямой формат работы','Оценка и реализация идут напрямую с разработчиком. Большую задачу можно начать с одного законченного этапа.')}<section class="p130-list-section"><div class="p130-shell"><div class="p129-section-head"><p class="p130-kicker">CAPABILITIES</p><h2>Основные направления.</h2></div><div class="p130-list">{rows(services)}</div></div></section><section class="p130-featured"><div class="p130-shell"><a class="p130-featured-card" href="/cases/sheetpilot-ai/"><div class="p130-featured-media"><img src="/assets/cases/sheetpilot-ai/sheetpilot-01-720w.webp" alt="SheetPilot AI" loading="lazy" decoding="async"></div><div class="p130-featured-copy"><p class="p130-kicker">FEATURED WORK</p><h2>SheetPilot AI</h2><p>Пример проекта, где интерфейс, серверная логика и обработка файла работают как единый пользовательский сценарий.</p><span class="p129-textlink">Открыть кейс и демо ↗</span></div></a></div></section><section class="p130-footer-cta"><div class="p130-shell"><div><h2>Есть задача, но непонятно направление?</h2><p>Пришлите текущее состояние и желаемый результат. Формат разработки можно определить после этого.</p></div><a class="p129-btn" href="https://t.me/Alexuys" target="_blank" rel="noopener noreferrer">Описать задачу ↗</a></div></section></main>'''
replace('/services/',services_main)

cases=[
('/cases/fin-planner/','Fin Planner','Telegram-сервис для учета доходов и расходов.','/assets/cases/fin-planner/fin-planner-original-800w.webp'),('/cases/swift-calendar/','Swift Calendar','Нативное iOS-приложение с календарными сценариями.','/assets/cases/swift-calendar/calendar-original-800w.webp'),('/cases/sheetpilot-ai/','SheetPilot AI','Веб-сервис для обработки Excel обычным языком.','/assets/cases/sheetpilot-ai/sheetpilot-01-720w.webp'),('/cases/seo-control-center/','SEO Control Center','Панель мониторинга поисковой видимости и индексации.','/assets/cases/seo-control-center/seo-control-center-card-02.svg'),('/cases/auto-crm/','CRM автосалона','Заявки, статусы и рабочие данные сотрудников.',None),('/cases/factory-catalog/','Каталог завода','B2B-каталог продукции и путь до заявки.',None),('/cases/taxi-app/','Приложение такси','Доработка существующего мобильного продукта.',None),('/cases/siteaudit-studio/','SiteAudit Studio','Инструмент анализа сайта и технических сигналов.',None),('/cases/freelance-os/','FreelanceOS','Рабочая система для управления фриланс-процессом.',None)]
tiles=[]
for i,(u,t,d,img) in enumerate(cases):
 cls='p130-tile p130-tile--wide' if i in (0,3) else 'p130-tile'
 if img: tiles.append(f'<a class="{cls}" href="{u}"><div class="p130-tile__media"><img src="{img}" alt="{html.escape(t)}" loading="lazy" decoding="async"></div><div class="p130-tile__body"><strong>{html.escape(t)}</strong><span>{html.escape(d)}</span></div></a>')
 else: tiles.append(f'<a class="{cls} p130-text-tile" href="{u}"><span class="p130-kicker">CASE {i+1:02d}</span><strong>{html.escape(t)}</strong><span>{html.escape(d)}</span></a>')
cases_main=f'''<main id="main-content" class="p130-hub" data-stage130-hub="cases">{hero('SELECTED WORK','Реальные проекты. <span>Без витрины из концептов.</span>','Кейсы показывают интерфейс, ограничения и то, что действительно было собрано. Сначала можно посмотреть работу, потом обсуждать новую задачу.','9 подробных кейсов','Telegram, web, iOS, CRM, SEO-инструменты и продукты для автоматизации.')}<section class="p130-list-section"><div class="p130-shell"><div class="p130-mosaic">{''.join(tiles)}</div></div></section><section class="p130-footer-cta"><div class="p130-shell"><div><h2>Нужен похожий результат?</h2><p>Можно прислать ссылку на близкий кейс и коротко написать, что должно работать в вашем проекте.</p></div><a class="p129-btn" href="https://t.me/Alexuys" target="_blank" rel="noopener noreferrer">Обсудить проект ↗</a></div></section></main>'''
replace('/cases/',cases_main)

guides=[('/guides/telegram-bot-cost/','Сколько стоит Telegram-бот','Какие части задачи влияют на стоимость сильнее количества кнопок.'),('/guides/telegram-bot-brief/','Как описать Telegram-бота','Короткий бриф без технического ТЗ.'),('/guides/bot-vs-mini-app-vs-web/','Бот, Mini App или веб','Как выбрать интерфейс под пользовательский сценарий.'),('/guides/development-cost/','Из чего складывается стоимость','Оценивать сценарии, данные и интеграции, а не страницы.'),('/guides/n8n-vs-backend/','n8n или backend','Где заканчивается workflow и начинается полноценная разработка.'),('/guides/n8n-vs-make/','n8n или Make','Как выбрать инструмент автоматизации.'),('/guides/repair-vs-rewrite/','Чинить или переписывать','Когда существующий код выгоднее сохранить.'),('/guides/site-vs-web-app/','Сайт или веб-приложение','Разница начинается с действий пользователя.'),('/guides/custom-crm-or-ready/','Своя CRM или готовая','Когда собственная система действительно оправдана.')]
guides_main=f'''<main id="main-content" class="p130-hub" data-stage130-hub="guides">{hero('DECISION GUIDES','Разобраться до разработки. <span>Без учебника на 40 экранов.</span>','Короткие материалы для решений, которые обычно приходится принимать до оценки проекта.','Практический формат','Каждый разбор отвечает на один выбор: формат, стоимость, подход или граница между инструментами.')}<section class="p130-list-section"><div class="p130-shell"><div class="p130-list">{rows(guides)}</div></div></section><section class="p130-footer-cta"><div class="p130-shell"><div><h2>Вашей ситуации нет в разборах?</h2><p>Опишите задачу своими словами. Для начала не требуется полноценное техническое задание.</p></div><a class="p129-btn" href="https://t.me/Alexuys" target="_blank" rel="noopener noreferrer">Задать вопрос ↗</a></div></section></main>'''
replace('/guides/',guides_main)

about_main=f'''<main id="main-content" class="p130-hub" data-stage130-hub="about">{hero('ABOUT','Разрабатываю сам. <span>И остаюсь внутри проекта.</span>','Работаю с сайтами, приложениями, Telegram-продуктами, автоматизацией и доработкой существующего кода. Не продаю фиксированный стек — сначала разбираю результат.','Независимая проверка','Публичный профиль Freelance.ru существует отдельно от этого сайта: отзывы, оценки и история работы доступны до первого сообщения.')}<section class="p130-editorial"><div class="p130-shell p130-editorial-grid"><div class="p130-editorial-statement"><p class="p130-kicker">HOW I WORK</p><h2>Меньше передачи задачи. Больше контекста.</h2><p>На старте важно понять, что уже есть, какой сценарий критичен и где заканчивается первый проверяемый результат. После этого проще выбрать технологию и оценить объём.</p><a class="p129-textlink" href="/services/">Посмотреть направления ↗</a></div><div class="p130-proof-stack"><a href="https://freelance.ru/gglalex" target="_blank" rel="me noopener noreferrer"><strong>20 отзывов</strong><span>в публичном профиле Freelance.ru</span></a><div><strong>6 лет</strong><span>опыта в открытом профиле</span></div><a href="/cases/"><strong>9 кейсов</strong><span>с реальными задачами и интерфейсами</span></a><a href="/demos/"><strong>4 демо</strong><span>которые можно открыть самостоятельно</span></a></div></div></section><section class="p130-footer-cta"><div class="p130-shell"><div><h2>Сначала можно просто показать проект.</h2><p>Ссылка, код, макет или несколько предложений о задаче достаточно для первого шага.</p></div><a class="p129-btn" href="https://t.me/Alexuys" target="_blank" rel="noopener noreferrer">Написать напрямую ↗</a></div></section></main>'''
replace('/about/',about_main)

freelance_main=f'''<main id="main-content" class="p130-hub" data-stage130-hub="freelance">{hero('DIRECT WORK','Фриланс-разработчик. <span>Без слоя между задачей и кодом.</span>','Подходит, когда нужен прямой контакт с исполнителем: новая разработка, отдельный модуль, интеграция или продолжение чужого проекта.','Как начать','Не нужно готовить большую презентацию. Достаточно показать текущее состояние и написать, что должно измениться.')}<section class="p130-list-section"><div class="p130-shell"><div class="p130-list">{rows([('/project-repair/','Продолжить существующий проект','Чужой код, ошибка, незавершённый релиз или новая функция.'),('/telegram-bots/','Собрать Telegram-продукт','Бот, заявки, оплаты, данные и интеграции.'),('/web-development/','Разработать веб-сервис','Интерфейс, данные, кабинет, каталог или MVP.'),('/n8n-automation/','Убрать ручную работу','Автоматизировать повторяющийся процесс между сервисами.'),('/cases/','Посмотреть реальные работы','Кейсы до первого сообщения.'),('/guides/','Разобраться в формате','Короткие материалы перед разработкой.')])}</div></div></section><section class="p130-editorial"><div class="p130-shell p130-editorial-grid"><div class="p130-editorial-statement"><p class="p130-kicker">PUBLIC REPUTATION</p><h2>Проверить можно до обращения.</h2><p>Отзывы и история находятся на внешней площадке, а не нарисованы внутри портфолио.</p></div><div class="p130-proof-stack"><a href="https://freelance.ru/gglalex" target="_blank" rel="me noopener noreferrer"><strong>Freelance.ru</strong><span>публичный профиль и история</span></a><a href="https://freelance.ru/reviews/gglalex/" target="_blank" rel="noopener noreferrer"><strong>20 отзывов</strong><span>отдельная страница отзывов</span></a></div></div></section><section class="p130-footer-cta"><div class="p130-shell"><div><h2>Есть одна конкретная задача?</h2><p>Это лучший формат для начала: понятный результат, который можно проверить отдельно.</p></div><a class="p129-btn" href="https://t.me/Alexuys" target="_blank" rel="noopener noreferrer">Написать задачу ↗</a></div></section></main>'''
replace('/freelance-developer/',freelance_main)
print('stage130 hub rebuild: services, cases, guides, about and freelance-developer replaced with new DOM')
