import test from 'node:test';
import assert from 'node:assert/strict';
import { isPublicAddress, parseTargetUrl } from '../src/network.js';
import { analyzeHtml, scoreIssues } from '../src/audit.js';

test('public IP classifier rejects private and loopback ranges',()=>{assert.equal(isPublicAddress('127.0.0.1'),false);assert.equal(isPublicAddress('10.0.0.1'),false);assert.equal(isPublicAddress('192.168.1.10'),false);assert.equal(isPublicAddress('169.254.1.1'),false);assert.equal(isPublicAddress('::1'),false);assert.equal(isPublicAddress('93.184.216.34'),true);assert.equal(isPublicAddress('2606:4700:4700::1111'),true)});
test('URL parser only accepts public-style HTTP(S) targets',()=>{assert.equal(parseTargetUrl('example.com').toString(),'https://example.com/');assert.equal(parseTargetUrl('http://example.com/a#fragment').toString(),'http://example.com/a');assert.throws(()=>parseTargetUrl('ftp://example.com'),/HTTP/);assert.throws(()=>parseTargetUrl('http://localhost:3000'),/Локальные/);assert.throws(()=>parseTargetUrl('https://user:pass@example.com'),/логином/)});
test('HTML analyzer extracts deterministic SEO and accessibility signals',()=>{const html='<!doctype html><html lang="ru"><head><title>Example title</title><meta name="description" content="Example description"><meta name="viewport" content="width=device-width"><link rel="canonical" href="/page/"></head><body><h1>Hello</h1><a href="/next/">Next</a><img src="x.jpg"></body></html>';const out=analyzeHtml(html,'https://example.com/page/');assert.equal(out.title,'Example title');assert.equal(out.h1Count,1);assert.equal(out.canonical,'https://example.com/page/');assert.equal(out.internalLinks[0],'https://example.com/next/');assert.equal(out.images.missingAlt,1);assert.equal(out.htmlLang,'ru')});
test('score is deterministic and never goes below zero',()=>{const result=scoreIssues([{category:'seo',severity:'critical'},{category:'seo',severity:'error'},{category:'crawl',severity:'warning'}]);assert.equal(result.overall,61);assert.equal(result.categories.seo,66);assert.equal(result.categories.crawl,95);const many=Array.from({length:20},()=>({category:'seo',severity:'critical'}));assert.equal(scoreIssues(many).overall,0)});
